cluster:
  zookeeper:
    hostPort: {ZK_ADDRESSES}
    sessionTimeout: 100000
naming:
  jetty:
    host: {NAMING_BIND_HOST}
    port: {NAMING_BIND_PORT}
    context_path: /
remote:
  gRPC:
    host: {BIND_HOST}
    port: {REMOTE_BIND_PORT}
agent_gRPC:
  gRPC:
    host: {BIND_HOST}
    port: {AGENT_GRPC_BIND_PORT}
agent_jetty:
  jetty:
    host: {AGENT_JETTY_BIND_HOST}
    port: {AGENT_JETTY_BIND_PORT}
    context_path: /
agent_stream:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: {UI_JETTY_BIND_HOST}
    port: {UI_JETTY_BIND_PORT}
    context_path: /
storage:
  elasticsearch:
    cluster_name: {ES_CLUSTER_NAME}
    cluster_transport_sniffer: true
    cluster_nodes: {ES_ADDRESSES}
    index_shards_number: 2
    index_replicas_number: 0
    ttl: 7
